export const spotifyIso = {
  // https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
  base: 'market=',
  get market() {
    return {
      Afghanistan: `${this.base}AF`,
      Albania: `${this.base}AL`,
      Algeria: `${this.base}DZ`,
      Andorra: `${this.base}AD`,
      Angola: `${this.base}AO`,
      Argentina: `${this.base}AR`,
      Armenia: `${this.base}AM`,
      Australia: `${this.base}AU`,
      Austria: `${this.base}AT`,
      Azerbaijan: `${this.base}AZ`,
      Bahrain: `${this.base}BH`,
      Bangladesh: `${this.base}BD`,
      Belarus: `${this.base}BY`,
      Belgium: `${this.base}BE`,
      Belize: `${this.base}BZ`,
      Benin: `${this.base}BJ`,
      Bhutan: `${this.base}BT`,
      Bolivia: `${this.base}BO`,
      'Bosnia and Herzegovina': `${this.base}BA`,
      Botswana: `${this.base}BW`,
      Brazil: `${this.base}BR`,
      Bulgaria: `${this.base}BG`,
      'Burkina Faso': `${this.base}BF`,
      Burundi: `${this.base}BI`,
      Cambodia: `${this.base}KH`,
      Cameroon: `${this.base}CM`,
      Canada: `${this.base}CA`,
      'Cape Verde': `${this.base}CV`,
      'Central African Republic': `${this.base}CF`,
      Chad: `${this.base}TD`,
      Chile: `${this.base}CL`,
      China: `${this.base}CN`,
      Colombia: `${this.base}CO`,
      Congo: `${this.base}CG`,
      'Costa Rica': `${this.base}CR`,
      'Côte d’Ivoire': `${this.base}CI`,
      Croatia: `${this.base}HR`,
      Cyprus: `${this.base}CY`,
      'Czech Republic': `${this.base}CZ`,
      Denmark: `${this.base}DK`,
      Djibouti: `${this.base}DJ`,
      'Dominican Republic': `${this.base}DO`,
      Ecuador: `${this.base}EC`,
      Egypt: `${this.base}EG`,
      'El Salvador': `${this.base}SV`,
      Estonia: `${this.base}EE`,
      Ethiopia: `${this.base}ET`,
      Fiji: `${this.base}FJ`,
      Finland: `${this.base}FI`,
      France: `${this.base}FR`,
      Gabon: `${this.base}GA`,
      Georgia: `${this.base}GE`,
      Germany: `${this.base}DE`,
      Ghana: `${this.base}GH`,
      Greece: `${this.base}GR`,
      Guatemala: `${this.base}GT`,
      Guinea: `${this.base}GN`,
      'Guinea-Bissau': `${this.base}GW`,
      Honduras: `${this.base}HN`,
      'Hong Kong': `${this.base}HK`,
      Hungary: `${this.base}HU`,
      Iceland: `${this.base}IS`,
      India: `${this.base}IN`,
      Indonesia: `${this.base}ID`,
      Ireland: `${this.base}IE`,
      Israel: `${this.base}IL`,
      Italy: `${this.base}IT`,
      Jamaica: `${this.base}JM`,
      Japan: `${this.base}JP`,
      Jordan: `${this.base}JO`,
      Kazakhstan: `${this.base}KZ`,
      Kenya: `${this.base}KE`,
      Kuwait: `${this.base}KW`,
      Kyrgyzstan: `${this.base}KG`,
      Laos: `${this.base}LA`,
      Latvia: `${this.base}LV`,
      Lebanon: `${this.base}LB`,
      Lesotho: `${this.base}LS`,
      Liberia: `${this.base}LR`,
      Libya: `${this.base}LY`,
      Liechtenstein: `${this.base}LI`,
      Lithuania: `${this.base}LT`,
      Luxembourg: `${this.base}LU`,
      Macau: `${this.base}MO`,
      'North Macedonia': `${this.base}MK`,
      Madagascar: `${this.base}MG`,
      Malawi: `${this.base}MW`,
      Malaysia: `${this.base}MY`,
      Mali: `${this.base}ML`,
      Malta: `${this.base}MT`,
      Mauritania: `${this.base}MR`,
      Mauritius: `${this.base}MU`,
      Mexico: `${this.base}MX`,
      Moldova: `${this.base}MD`,
      Monaco: `${this.base}MC`,
      Mongolia: `${this.base}MN`,
      Montenegro: `${this.base}ME`,
      Morocco: `${this.base}MA`,
      Mozambique: `${this.base}MZ`,
      Myanmar: `${this.base}MM`,
      Namibia: `${this.base}NA`,
      Nepal: `${this.base}NP`,
      Netherlands: `${this.base}NL`,
      'New Zealand': `${this.base}NZ`,
      Nicaragua: `${this.base}NI`,
      Niger: `${this.base}NE`,
      Nigeria: `${this.base}NG`,
      Norway: `${this.base}NO`,
      Oman: `${this.base}OM`,
      Pakistan: `${this.base}PK`,
      Panama: `${this.base}PA`,
      'Papua New Guinea': `${this.base}PG`,
      Paraguay: `${this.base}PY`,
      Peru: `${this.base}PE`,
      Philippines: `${this.base}PH`,
      Poland: `${this.base}PL`,
      Portugal: `${this.base}PT`,
      Qatar: `${this.base}QA`,
      Romania: `${this.base}RO`,
      Russia: `${this.base}RU`,
      Rwanda: `${this.base}RW`,
      'Saudi Arabia': `${this.base}SA`,
      Senegal: `${this.base}SN`,
      Serbia: `${this.base}RS`,
      Singapore: `${this.base}SG`,
      Slovakia: `${this.base}SK`,
      Slovenia: `${this.base}SI`,
      'South Africa': `${this.base}ZA`,
      'South Korea': `${this.base}KR`,
      Spain: `${this.base}ES`,
      'Sri Lanka': `${this.base}LK`,
      Sweden: `${this.base}SE`,
      Switzerland: `${this.base}CH`,
      Taiwan: `${this.base}TW`,
      Tanzania: `${this.base}TZ`,
      Thailand: `${this.base}TH`,
      Tunisia: `${this.base}TN`,
      Turkey: `${this.base}TR`,
      Ukraine: `${this.base}UA`,
      'United Arab Emirates': `${this.base}AE`,
      'United Kingdom': `${this.base}GB`,
      USA: `${this.base}US`,
      Uruguay: `${this.base}UY`,
      Venezuela: `${this.base}VE`,
      Vietnam: `${this.base}VN`,
      Zambia: `${this.base}ZM`,
      Zimbabwe: `${this.base}ZW`,
    };
  },
};
