const EPartners = () => {
  return (
    <div className='eFooter__partners__track'>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/Apos.png'
          alt='Apos'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/Audient.svg'
          alt='Audient'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/Beyerdynamic.svg'
          alt='Beyerdynamic'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/ElectroVoice.png'
          alt='Electro Voice'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/Evo.svg'
          alt='Evo'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/Focusrite.png'
          alt='Focusrite'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/Neumann.webp'
          alt='Neumann'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/Rode.svg'
          alt='Rode'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/Schiit.png'
          alt='Schiit'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/Shure.svg'
          alt='Shure'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/SMSL.png'
          alt='SMSL'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/SolidStateLogic.svg'
          alt='Solid State Logic'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
      <picture>
        <img
          src='src/ecommerce/assets/production-images/compressed-company-logos/UAudio.png'
          alt='UAudio'
          draggable='false'
          loading='lazy'
          decoding='async'
          fetchpriority='low'
        />
      </picture>
    </div>
  );
};
export default EPartners;
