import { ProductType } from '../../types/ProductType';

export const ProductDatabase: ProductType[] = [
  {
    sku: 'Avid-MBOX-Studio',
    stock: 2,
    company: 'Avid',
    unit: 'MBOX Studio',
    description:
      '21-in/22-out, 24-bit/192kHz Desktop USB-C Audio Interface with 4 Mic Preamps, Stereo Bluetooth I/O, MIDI I/O, 2 Headphone Outputs, Loopback Mixing, Monitor Controller with Talkback, Re-amping, and Real-time Effects - Mac/PC',
    price: 899.0,
    category: 'interfaces',
    productshowcase: false,
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-5.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-5.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Avid/interface/mbox-studio/avid-mbox-studio-usb-audio-interface-5.jpg',
      ],
    },
  },
  {
    sku: 'focusrite-scarlett-solo-3rd-gen',
    stock: 2,
    company: 'Focusrite',
    unit: 'Scarlett Solo 3rd Gen',
    description:
      'The third-generation Scarlett Solo provides singer-songwriters with a reassuringly easy recording process. Equipped with high performance 24-bit/192kHz AD-DA converters, Scarlett guarantees the same professional sound quality throughout the third-generation range. Its features include a single upgraded third-generation Scarlett mic preamp: with a switchable Air setting to reproduce the Air effect of Focusrites original ISA mic preamp, giving your vocal recordings a brighter and more open sound. The high impedance, high-headroom instrument input allows you to record guitar or bass without any clipping or unwanted distortion, while Gain Halo metering makes it easy for you to set the input level. And Scarlett Solos balanced outputs are hum-free when connecting studio monitors with balanced inputs, so youll always have pristine audio playback.',
    price: 129.99,
    category: 'interfaces',
    productshowcase: false,
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interfacescarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-6.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interfacescarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-6.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interfacescarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interface/scarlett-solo-3rd-gen/focusrite-scarlett-solo-3rd-gen-6.jpg',
      ],
    },
  },
  {
    sku: 'focusrite-scarlett-2i2-3rd-gen',
    stock: 2,
    company: 'Focusrite',
    unit: 'Scarlett 2i2 3rd Gen',
    description:
      'The 2i2 features two upgraded third-generation Scarlett mic preamps: with optional Air setting to reproduce the Air effect of Focusrites original ISA mic preamp, giving your vocal and acoustic recordings a brighter and more open sound. Equipped with high performance 24-bit/192kHz AD-DA converters, Scarlett guarantees the same professional sound quality throughout the third-generation range. The high impedance, high-headroom instrument inputs allow you to record guitar or bass without any clipping or unwanted distortion, while Gain Halo metering makes it easy for you to set the input level. ',
    price: 189.99,
    category: 'interfaces',
    productshowcase: true,
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-6.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-6.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Focusrite/interface/scarlett-2i2-3rd-gen/focusrite-scarlett-2i2-3rd-gen-6.jpg',
      ],
    },
  },
  {
    sku: 'uaudio-apollo-solo',
    stock: 2,
    company: 'UAudio',
    unit: 'Solo',
    description:
      'Apollo Solo is the world’s finest Thunderbolt 3-powered desktop recording audio interface for Mac and Windows, giving you class-leading audio conversion, two mic preamps — so you can record through preamps from Neve, API, SSL, and more — and a suite of included UAD plug-ins for recording album-quality results, with near-zero latency.',
    price: 499.0,
    category: 'interfaces',
    productshowcase: false,
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-solo/uaudio-apollo-solo-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-solo/uaudio-apollo-solo-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-solo/uaudio-apollo-solo-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-solo/uaudio-apollo-solo-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-solo/uaudio-apollo-solo-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-solo/uaudio-apollo-solo-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-solo/uaudio-apollo-solo-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-solo/uaudio-apollo-solo-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-solo/uaudio-apollo-solo-3.jpg',
      ],
    },
  },
  {
    sku: 'uaudio-apollo-twin-mk-ii',
    stock: 2,
    company: 'UAudio',
    unit: 'Twin Mk II',
    description:
      'Apollo Twin MkII features two Unison-enabled mic preamps, letting you track through exacting mic preamp emulations from Neve, SSL, API, Manley, and Universal Audio. An Apollo exclusive, Unison technology nails the tone of these sought-after tube and solid state mic pres — including their input impedance, gain stage “sweet spots,” and the component-level circuit behaviors of the original hardware. The secret to Unison is its hardware-software integration between Apollo’s mic preamps and its onboard UAD-2 DUO Core DSP Acceleration. Simply place a Unison preamp plug-in on your mic input, and tap into the classic sounds of the world’s most recorded mic preamps. ',
    price: 799.0,
    category: 'interfaces',
    productshowcase: false,
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-twin-mkii/uaudio-apollo-twin-mkii-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-twin-mkii/uaudio-apollo-twin-mkii-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-twin-mkii/uaudio-apollo-twin-mkii-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-twin-mkii/uaudio-apollo-twin-mkii-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-twin-mkii/uaudio-apollo-twin-mkii-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-twin-mkii/uaudio-apollo-twin-mkii-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-twin-mkii/uaudio-apollo-twin-mkii-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-twin-mkii/uaudio-apollo-twin-mkii-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-twin-mkii/uaudio-apollo-twin-mkii-3.jpg',
      ],
    },
  },
  {
    sku: 'uaudio-apollo-twin-x',
    stock: 2,
    company: 'UAudio',
    unit: 'Apollo Twin X',
    description:
      'Apollo Twin X gives musicians and producers elite-class audio conversion with the tone, feel, and flow of analog recording. Letting you record through preamps from Neve, API, Manley, and more — with near‑zero latency — Apollo Twin X is born to make records.',
    price: 999.0,
    category: 'interfaces',
    productshowcase: false,
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-twin-x/uaudio-apollo-twin-x-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-twin-x/uaudio-apollo-twin-x-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-twin-x/uaudio-apollo-twin-x-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-twin-x/uaudio-apollo-twin-x-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-twin-x/uaudio-apollo-twin-x-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-twin-x/uaudio-apollo-twin-x-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-twin-x/uaudio-apollo-twin-x-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-twin-x/uaudio-apollo-twin-x-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-twin-x/uaudio-apollo-twin-x-3.jpg',
      ],
    },
  },
  {
    sku: 'uaudio-apollo-x4',
    stock: 2,
    company: 'UAudio',
    unit: 'Apollo X4',
    description:
      'Apollo x4 gives engineers and producers recording larger projects the same professional analog tones heard on your favorite records with four onboard Unison™ mic preamps. With elite‑class conversion and QUAD Core UAD plug-in processing, Apollo x4 lets you record through preamps from Neve, API, Manley, SSL, and more — with near‑zero latency — giving you a fully-stocked analog studio, right on your desktop. ',
    price: 1999.0,
    category: 'interfaces',
    productshowcase: false,
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-x4/uaudio-apollo-x4-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-x4/uaudio-apollo-x4-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/apollo-x4/uaudio-apollo-x4-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-x4/uaudio-apollo-x4-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-x4/uaudio-apollo-x4-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/apollo-x4/uaudio-apollo-x4-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-x4/uaudio-apollo-x4-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-x4/uaudio-apollo-x4-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/apollo-x4/uaudio-apollo-x4-3.jpg',
      ],
    },
  },
  {
    sku: 'uaudio-volt-1',
    stock: 2,
    company: 'UAudio',
    unit: 'Volt 1',
    description:
      'We created the Volt 1 USB audio interface for singers, guitarists, and content creators who want to easily record audio with legendary studio sound. Plug right into your Mac, PC, iPad, or iPhone and Volt just shows up — ready to capture your inspiration with professional sound, courtesy of Universal Audio.',
    price: 189.0,
    category: 'interfaces',
    productshowcase: false,
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/volt-1/uaudio-volt-1-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/volt-1/uaudio-volt-1-2.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/volt-1/uaudio-volt-1-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/volt-1/uaudio-volt-1-2.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/volt-1/uaudio-volt-1-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/volt-1/uaudio-volt-1-2.jpg',
      ],
    },
  },
  {
    sku: 'uaudio-volt-2',
    stock: 2,
    company: 'UAudio',
    unit: 'Volt 2',
    description:
      'Volt 2 is the perfect USB audio interface for creative collaborators — from musicians and songwriters to livestreamers and podcasters — who want to easily record audio with legendary studio sound. Plug right into your Mac, PC, iPad, or iPhone and Volt just shows up, ready to capture your inspiration with professional sound, courtesy of Universal Audio.',
    price: 189.0,
    category: 'interfaces',
    productshowcase: false,
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/volt-2/uaudio-volt-2-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/volt-2/uaudio-volt-2-2.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/volt-2/uaudio-volt-2-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/volt-2/uaudio-volt-2-2.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/volt-2/uaudio-volt-2-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/volt-2/uaudio-volt-2-2.jpg',
      ],
    },
  },
  {
    sku: 'uaudio-volt-4',
    stock: 2,
    company: 'UAudio',
    unit: 'Volt 4',
    description:
      'Volt 4 is the perfect USB audio interface for creative collaborators who want to easily record audio projects with professional studio sound. Plug right into your Mac, PC, iPad, or iPhone and Volt just shows up, ready to capture your inspiration with professional sound, courtesy of Universal Audio.',
    price: 259.0,
    category: 'interfaces',
    productshowcase: false,
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/volt-4/uaudio-volt-4-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/UAudio/interface/volt-4/uaudio-volt-4-2.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/volt-4/uaudio-volt-4-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/UAudio/interface/volt-4/uaudio-volt-4-2.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/volt-4/uaudio-volt-4-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/UAudio/interface/volt-4/uaudio-volt-4-2.jpg',
      ],
    },
  },
  {
    sku: 'beyerdynamic-t5',
    stock: 2,
    company: 'Beyerdynamic',
    unit: 'T5',
    description: 'High-end Tesla Headphones (3rd Generation) closed',
    price: 899.0,
    productshowcase: false,
    category: 'headphones',
    wearStyle: 'closed-back',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/T5/beyerdynamic-t5-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/T5/beyerdynamic-t5-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/T5/beyerdynamic-t5-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/T5/beyerdynamic-t5-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/T5/beyerdynamic-t5-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/T5/beyerdynamic-t5-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/T5/beyerdynamic-t5-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/T5/beyerdynamic-t5-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/T5/beyerdynamic-t5-3.jpg',
      ],
    },
  },
  {
    sku: 'beyerdynamic-t1',
    stock: 2,
    company: 'Beyerdynamic',
    unit: 'T1',
    description: 'High-end Tesla headphones (3rd generation) open',
    price: 899.0,
    productshowcase: false,
    category: 'headphones',
    wearStyle: 'open-back',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/T1/beyerdynamic-t1-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/T1/beyerdynamic-t1-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/T1/beyerdynamic-t1-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/T1/beyerdynamic-t1-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/T1/beyerdynamic-t1-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/T1/beyerdynamic-t1-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/T1/beyerdynamic-t1-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/T1/beyerdynamic-t1-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/T1/beyerdynamic-t1-3.jpg',
      ],
    },
  },
  {
    sku: 'beyerdynamic-dt-900-pro-x',
    stock: 2,
    company: 'Beyerdynamic',
    unit: 'DT 900 PRO X',
    description: 'Studio headphones for critical listening, mixing & mastering (open-back)',
    price: 349.0,
    productshowcase: false,
    category: 'headphones',
    wearStyle: 'open-back',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 900 PRO X/beyerdynamic-dt-900-pro-x-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 900 PRO X/beyerdynamic-dt-900-pro-x-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 900 PRO X/beyerdynamic-dt-900-pro-x-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 900 PRO X/beyerdynamic-dt-900-pro-x-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 900 PRO X/beyerdynamic-dt-900-pro-x-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 900 PRO X/beyerdynamic-dt-900-pro-x-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 900 PRO X/beyerdynamic-dt-900-pro-x-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 900 PRO X/beyerdynamic-dt-900-pro-x-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 900 PRO X/beyerdynamic-dt-900-pro-x-3.jpg',
      ],
    },
  },
  {
    sku: 'beyerdynamic-dt-700-pro-x',
    stock: 2,
    company: 'Beyerdynamic',
    unit: 'DT 700 PRO X',
    description: 'Studio headphones for recording & monitoring (closed)',
    price: 259.0,
    productshowcase: true,
    category: 'headphones',
    wearStyle: 'closed-back',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 700 PRO X/beyerdynamic-dt-700-pro-x-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 700 PRO X/beyerdynamic-dt-700-pro-x-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 700 PRO X/beyerdynamic-dt-700-pro-x-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 700 PRO X/beyerdynamic-dt-700-pro-x-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 700 PRO X/beyerdynamic-dt-700-pro-x-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 700 PRO X/beyerdynamic-dt-700-pro-x-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 700 PRO X/beyerdynamic-dt-700-pro-x-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 700 PRO X/beyerdynamic-dt-700-pro-x-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 700 PRO X/beyerdynamic-dt-700-pro-x-3.jpg',
      ],
    },
  },
  {
    sku: 'beyerdynamic-dt-1990-pro',
    stock: 2,
    company: 'Beyerdynamic',
    unit: 'DT 1990 PRO',
    description: 'Tesla studio reference headphones for mixing and mastering (open)',
    price: 499.0,
    productshowcase: false,
    category: 'headphones',
    wearStyle: 'open-back',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 1990 PRO/beyerdynamic-dt-1990-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 1990 PRO/beyerdynamic-dt-1990-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 1990 PRO/beyerdynamic-dt-1990-pro-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 1990 PRO/beyerdynamic-dt-1990-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 1990 PRO/beyerdynamic-dt-1990-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 1990 PRO/beyerdynamic-dt-1990-pro-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 1990 PRO/beyerdynamic-dt-1990-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 1990 PRO/beyerdynamic-dt-1990-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 1990 PRO/beyerdynamic-dt-1990-pro-3.jpg',
      ],
    },
  },
  {
    sku: 'beyerdynamic-dt-1770-pro',
    stock: 2,
    company: 'Beyerdynamic',
    unit: 'DT 1770 PRO',
    description: 'Tesla studio reference headphones for mixing, mastering, monitoring (closed)',
    price: 499.0,
    productshowcase: true,
    category: 'headphones',
    wearStyle: 'closed-back',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 1770 PRO/beyerdynamic-dt-1770-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 1770 PRO/beyerdynamic-dt-1770-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 1770 PRO/beyerdynamic-dt-1770-pro-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 1770 PRO/beyerdynamic-dt-1770-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 1770 PRO/beyerdynamic-dt-1770-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 1770 PRO/beyerdynamic-dt-1770-pro-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 1770 PRO/beyerdynamic-dt-1770-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 1770 PRO/beyerdynamic-dt-1770-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 1770 PRO/beyerdynamic-dt-1770-pro-3.jpg',
      ],
    },
  },
  {
    sku: 'beyerdynamic-dt-990-black-se',
    stock: 2,
    company: 'Beyerdynamic',
    unit: 'DT 990 Black Special Edition',
    description: 'Hi-fi headphones (open)',
    price: 159.0,
    productshowcase: false,
    category: 'headphones',
    wearStyle: 'open-back',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 990 Black Special Edition/beyerdynamic-dt-990-black-special-edition-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 990 Black Special Edition/beyerdynamic-dt-990-black-special-edition-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 990 Black Special Edition/beyerdynamic-dt-990-black-special-edition-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 990 Black Special Edition/beyerdynamic-dt-990-black-special-edition-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 990 Black Special Edition/beyerdynamic-dt-990-black-special-edition-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 990 Black Special Edition/beyerdynamic-dt-990-black-special-edition-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 990 Black Special Edition/beyerdynamic-dt-990-black-special-edition-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 990 Black Special Edition/beyerdynamic-dt-990-black-special-edition-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 990 Black Special Edition/beyerdynamic-dt-990-black-special-edition-3.jpg',
      ],
    },
  },
  {
    sku: 'beyerdynamic-dt-990-pro',
    stock: 2,
    company: 'Beyerdynamic',
    unit: 'DT 990 PRO',
    description: 'Studio headphones for mixing and mastering (open)',
    price: 159.0,
    productshowcase: true,
    category: 'headphones',
    wearStyle: 'open-back',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 990 PRO/beyerdynamic-dt-990-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 990 PRO/beyerdynamic-dt-990-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 990 PRO/beyerdynamic-dt-990-pro-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 990 PRO/beyerdynamic-dt-990-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 990 PRO/beyerdynamic-dt-990-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 990 PRO/beyerdynamic-dt-990-pro-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 990 PRO/beyerdynamic-dt-990-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 990 PRO/beyerdynamic-dt-990-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 990 PRO/beyerdynamic-dt-990-pro-3.jpg',
      ],
    },
  },
  {
    sku: 'beyerdynamic-dt-880-pro',
    stock: 2,
    company: 'Beyerdynamic',
    unit: 'DT 880 PRO',
    description: 'Studio headphones for mixing and mastering (semi-open)',
    price: 199.0,
    productshowcase: false,
    category: 'headphones',
    wearStyle: 'semi-open',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 880 PRO/beyerdynamic-dt-880-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 880 PRO/beyerdynamic-dt-880-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 880 PRO/beyerdynamic-dt-880-pro-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 880 PRO/beyerdynamic-dt-880-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 880 PRO/beyerdynamic-dt-880-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 880 PRO/beyerdynamic-dt-880-pro-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 880 PRO/beyerdynamic-dt-880-pro-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 880 PRO/beyerdynamic-dt-880-pro-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 880 PRO/beyerdynamic-dt-880-pro-3.jpg',
      ],
    },
  },
  {
    sku: 'beyerdynamic-dt-770-pro',
    stock: 2,
    company: 'Beyerdynamic',
    unit: 'DT 770 PRO',
    description: 'Reference headphones for control and monitoring purpose (closed)',
    price: 159.0,
    productshowcase: true,
    category: 'headphones',
    wearStyle: 'closed-back',
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 770 PRO/beyerdynamic-dt-770-pro-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 770 PRO/beyerdynamic-dt-770-pro-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 770 PRO/beyerdynamic-dt-770-pro-1.jpg'],
    },
  },
  {
    sku: 'beyerdynamic-dt-990-e',
    stock: 2,
    company: 'Beyerdynamic',
    unit: 'DT 990 Edition',
    description: 'Hi-fi headphones (open)',
    price: 175.0,
    productshowcase: false,
    category: 'headphones',
    wearStyle: 'open-back',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 990 Edition/beyerdynamic-dt-990-edition-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 990 Edition/beyerdynamic-dt-990-edition-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Beyerdynamic/headphone/DT 990 Edition/beyerdynamic-dt-990-edition-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 990 Edition/beyerdynamic-dt-990-edition-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 990 Edition/beyerdynamic-dt-990-edition-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Beyerdynamic/headphone/DT 990 Edition/beyerdynamic-dt-990-edition-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 990 Edition/beyerdynamic-dt-990-edition-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 990 Edition/beyerdynamic-dt-990-edition-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Beyerdynamic/headphone/DT 990 Edition/beyerdynamic-dt-990-edition-3.jpg',
      ],
    },
  },
  {
    sku: 'evo-4',
    stock: 2,
    company: 'Evo',
    unit: '4',
    description: '2in | 2out Audio Interface',
    price: 129.0,
    productshowcase: false,
    category: 'interfaces',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/4/evo-4-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/4/evo-4-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/4/evo-4-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/4/evo-4-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/4/evo-4-5.webp',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/4/evo-4-6.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/4/evo-4-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/4/evo-4-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/4/evo-4-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/4/evo-4-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/4/evo-4-5.webp',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/4/evo-4-6.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/4/evo-4-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/4/evo-4-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/4/evo-4-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/4/evo-4-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/4/evo-4-5.webp',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/4/evo-4-6.jpg',
      ],
    },
  },
  {
    sku: 'evo-8',
    stock: 2,
    company: 'Evo',
    unit: '8',
    description: '4in | 4out Audio Interface',
    price: 199.0,
    productshowcase: false,
    category: 'interfaces',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/8/evo-8-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/8/evo-8-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/8/evo-8-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/8/evo-8-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/8/evo-8-5.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/8/evo-8-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/8/evo-8-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/8/evo-8-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/8/evo-8-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/8/evo-8-5.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/8/evo-8-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/8/evo-8-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/8/evo-8-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/8/evo-8-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/8/evo-8-5.jpg',
      ],
    },
  },
  {
    sku: 'evo-16',
    stock: 2,
    company: 'Evo',
    unit: '16',
    description: '24in | 24out Audio Interface',
    price: 499.0,
    productshowcase: false,
    category: 'interfaces',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/16/evo-16-1.png',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/16/evo-16-2.png',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/16/evo-16-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/16/evo-16-4.webp',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/16/evo-16-5.png',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/16/evo-16-1.png',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/16/evo-16-2.png',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/16/evo-16-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/16/evo-16-4.webp',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/16/evo-16-5.png',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/16/evo-16-1.png',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/16/evo-16-2.png',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/16/evo-16-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/16/evo-16-4.webp',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/16/evo-16-5.png',
      ],
    },
  },
  {
    sku: 'evo-sp8',
    stock: 2,
    company: 'Evo',
    unit: 'SP8',
    description: '8 Channel Smart Preamp with AD/DA',
    price: 499.0,
    productshowcase: false,
    category: 'interfaces',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/SP8/evo-sp8-1.webp',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/SP8/evo-sp8-2.png',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/SP8/evo-sp8-3.png',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/SP8/evo-sp8-4.png',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Evo/interface/SP8/evo-sp8-5.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/SP8/evo-sp8-1.webp',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/SP8/evo-sp8-2.png',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/SP8/evo-sp8-3.png',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/SP8/evo-sp8-4.png',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Evo/interface/SP8/evo-sp8-5.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/SP8/evo-sp8-1.webp',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/SP8/evo-sp8-2.png',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/SP8/evo-sp8-3.png',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/SP8/evo-sp8-4.png',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Evo/interface/SP8/evo-sp8-5.jpg',
      ],
    },
  },
  {
    sku: 'audient-id4',
    stock: 2,
    company: 'Audient',
    unit: 'iD4',
    description: '2in | 2out Audio Interface',
    price: 199.0,
    productshowcase: false,
    category: 'interfaces',
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Audient/interface/iD4/audient-id4-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-660x660/Audient/interface/iD4/audient-id4-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-1000x1000/Audient/interface/iD4/audient-id4-1.jpg'],
    },
  },
  {
    sku: 'audient-id14',
    stock: 2,
    company: 'Audient',
    unit: 'iD14',
    description: '10in | 6out Audio Interface',
    price: 298.99,
    productshowcase: false,
    category: 'interfaces',
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Audient/interface/iD14/audient-id14-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-660x660/Audient/interface/iD14/audient-id14-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-1000x1000/Audient/interface/iD14/audient-id14-1.jpg'],
    },
  },
  {
    sku: 'audient-id22',
    stock: 2,
    company: 'Audient',
    unit: 'iD22',
    description: '10in | 14out audio interface',
    price: 499.99,
    productshowcase: false,
    category: 'interfaces',
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Audient/interface/iD22/audient-id22-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-660x660/Audient/interface/iD22/audient-id22-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-1000x1000/Audient/interface/iD22/audient-id22-1.jpg'],
    },
  },
  {
    sku: 'audient-id24',
    stock: 2,
    company: 'Audient',
    unit: 'iD24',
    description: '10in | 14out Audio Interface',
    price: 399.0,
    productshowcase: true,
    category: 'interfaces',
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Audient/interface/iD24/audient-id24-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-660x660/Audient/interface/iD24/audient-id24-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-1000x1000/Audient/interface/iD24/audient-id24-1.jpg'],
    },
  },
  {
    sku: 'audient-id44',
    stock: 2,
    company: 'Audient',
    unit: 'iD44',
    description: '20in | 24out Audio Interface',
    price: 699.0,
    productshowcase: false,
    category: 'interfaces',
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Audient/interface/iD44/audient-id44-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-660x660/Audient/interface/iD44/audient-id44-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-1000x1000/Audient/interface/iD44/audient-id44-1.jpg'],
    },
  },
  {
    sku: 'solid-state-logic-ssl2',
    stock: 2,
    company: 'Solid State Logic',
    unit: 'SSL2',
    description: '2in | 2out USB-C Audio Interface',
    price: 179.99,
    productshowcase: false,
    category: 'interfaces',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-4.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-4.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL2/solid-state-logic-ssl2-4.jpg',
      ],
    },
  },
  {
    sku: 'solid-state-logic-ssl2+',
    stock: 2,
    company: 'Solid State Logic',
    unit: 'SSL 2+',
    description: '2in | 4out USB-C Audio Interface',
    price: 229.99,
    productshowcase: false,
    category: 'interfaces',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL 2+/solid-state-logic-ssl2+-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL 2+/solid-state-logic-ssl2+-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL 2+/solid-state-logic-ssl2+-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL 2+/solid-state-logic-ssl2+-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL 2+/solid-state-logic-ssl2+-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL 2+/solid-state-logic-ssl2+-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL 2+/solid-state-logic-ssl2+-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL 2+/solid-state-logic-ssl2+-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL 2+/solid-state-logic-ssl2+-3.jpg',
      ],
    },
  },
  {
    sku: 'solid-state-logic-ssl12',
    stock: 2,
    company: 'Solid State Logic',
    unit: 'SSL 12',
    description: '12in | 8out USB-C Audio Interface',
    price: 499.99,
    productshowcase: false,
    category: 'interfaces',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-5.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-5.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Solid State Logic/interface/SSL 12/solid-state-logic-ssl12-5.jpg',
      ],
    },
  },
  {
    sku: 'Electro-Voice-RE20-BLACK-EDITION',
    stock: 2,
    company: 'Electro-Voice',
    unit: 'RE20 Black Edition',
    description: "Broadcast announcer's microphone with Variable‑D",
    price: 498.0,
    productshowcase: false,
    category: 'microphones',
    polarPattern: 'cardioid',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Electro-Voice/microphone/RE20-BLACK/electro-voice-re20-black-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Electro-Voice/microphone/RE20-BLACK/electro-voice-re20-black-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Electro-Voice/microphone/RE20-BLACK/electro-voice-re20-black-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Electro-Voice/microphone/RE20-BLACK/electro-voice-re20-black-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Electro-Voice/microphone/RE20-BLACK/electro-voice-re20-black-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Electro-Voice/microphone/RE20-BLACK/electro-voice-re20-black-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Electro-Voice/microphone/RE20-BLACK/electro-voice-re20-black-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Electro-Voice/microphone/RE20-BLACK/electro-voice-re20-black-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Electro-Voice/microphone/RE20-BLACK/electro-voice-re20-black-3.jpg',
      ],
    },
  },
  {
    sku: 'Electro-Voice-RE20',
    stock: 2,
    company: 'Electro-Voice',
    unit: 'RE20',
    description: "Broadcast announcer's microphone with Variable‑D",
    price: 498.0,
    productshowcase: false,
    category: 'microphones',
    polarPattern: 'cardioid',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Electro-Voice/microphone/RE20/electro-voice-re20-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Electro-Voice/microphone/RE20/electro-voice-re20-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Electro-Voice/microphone/RE20/electro-voice-re20-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Electro-Voice/microphone/RE20/electro-voice-re20-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Electro-Voice/microphone/RE20/electro-voice-re20-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Electro-Voice/microphone/RE20/electro-voice-re20-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Electro-Voice/microphone/RE20/electro-voice-re20-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Electro-Voice/microphone/RE20/electro-voice-re20-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Electro-Voice/microphone/RE20/electro-voice-re20-3.jpg',
      ],
    },
  },
  {
    sku: 'Shure-SM7B',
    stock: 2,
    company: 'Shure',
    unit: 'SM7B',
    description: 'Vocal Microphone',
    price: 399.0,
    productshowcase: true,
    category: 'microphones',
    polarPattern: 'cardioid',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM7B/shure-sm7b-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM7B/shure-sm7b-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM7B/shure-sm7b-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM7B/shure-sm7b-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM7B/shure-sm7b-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM7B/shure-sm7b-6.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM7B/shure-sm7b-7.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM7B/shure-sm7b-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM7B/shure-sm7b-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM7B/shure-sm7b-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM7B/shure-sm7b-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM7B/shure-sm7b-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM7B/shure-sm7b-6.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM7B/shure-sm7b-7.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM7B/shure-sm7b-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM7B/shure-sm7b-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM7B/shure-sm7b-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM7B/shure-sm7b-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM7B/shure-sm7b-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM7B/shure-sm7b-6.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM7B/shure-sm7b-7.jpg',
      ],
    },
  },
  {
    sku: 'Shure-SM58',
    stock: 2,
    company: 'Shure',
    unit: 'SM58',
    description: 'Vocal Microphone',
    price: 99.0,
    productshowcase: false,
    category: 'microphones',
    polarPattern: 'cardioid',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM58/shure-sm58-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM58/shure-sm58-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM58/shure-sm58-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM58/shure-sm58-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM58/shure-sm58-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Shure/microphone/SM58/shure-sm58-6.webp',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM58/shure-sm58-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM58/shure-sm58-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM58/shure-sm58-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM58/shure-sm58-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM58/shure-sm58-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Shure/microphone/SM58/shure-sm58-6.webp',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM58/shure-sm58-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM58/shure-sm58-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM58/shure-sm58-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM58/shure-sm58-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM58/shure-sm58-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Shure/microphone/SM58/shure-sm58-6.webp',
      ],
    },
  },
  {
    sku: 'Rode-NT1',
    stock: 2,
    company: 'Rode',
    unit: 'NT1',
    description: 'Large-diaphragm Cardioid Condenser Microphone',
    price: 269.0,
    productshowcase: false,
    category: 'microphones',
    polarPattern: 'cardioid',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/NT1/rode-nt1-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/NT1/rode-nt1-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/NT1/rode-nt1-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/NT1/rode-nt1-4.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/NT1/rode-nt1-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/NT1/rode-nt1-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/NT1/rode-nt1-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/NT1/rode-nt1-4.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/NT1/rode-nt1-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/NT1/rode-nt1-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/NT1/rode-nt1-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/NT1/rode-nt1-4.jpg',
      ],
    },
  },
  {
    sku: 'Rode-NT1-A',
    stock: 2,
    company: 'Rode',
    unit: 'NT1-A',
    description: 'Large-diaphragm Cardioid Condenser Microphone',
    price: 199.0,
    productshowcase: false,
    category: 'microphones',
    polarPattern: 'cardioid',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/NT1-A/rode-nt1-a-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/NT1-A/rode-nt1-a-2.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/NT1-A/rode-nt1-a-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/NT1-A/rode-nt1-a-2.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/NT1-A/rode-nt1-a-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/NT1-A/rode-nt1-a-2.jpg',
      ],
    },
  },
  {
    sku: 'Rode-PodMic',
    stock: 2,
    company: 'Rode',
    unit: 'PodMic',
    description: 'Dynamic Broadcast Microphone',
    price: 99.0,
    productshowcase: true,
    category: 'microphones',
    polarPattern: 'cardioid',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMic/rode-podmic-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMic/rode-podmic-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMic/rode-podmic-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMic/rode-podmic-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMic/rode-podmic-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMic/rode-podmic-6.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMic/rode-podmic-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMic/rode-podmic-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMic/rode-podmic-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMic/rode-podmic-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMic/rode-podmic-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMic/rode-podmic-6.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMic/rode-podmic-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMic/rode-podmic-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMic/rode-podmic-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMic/rode-podmic-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMic/rode-podmic-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMic/rode-podmic-6.jpg',
      ],
    },
  },
  {
    sku: 'Rode-PodMic-USB',
    stock: 2,
    company: 'Rode',
    unit: 'PodMic USB',
    description: 'Dynamic Broadcast Microphone',
    price: 199.99,
    productshowcase: false,
    category: 'microphones',
    polarPattern: 'cardioid',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMicUSB/rode-podmic-usb-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMicUSB/rode-podmic-usb-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMicUSB/rode-podmic-usb-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMicUSB/rode-podmic-usb-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMicUSB/rode-podmic-usb-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMicUSB/rode-podmic-usb-6.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Rode/microphone/PodMicUSB/rode-podmic-usb-7.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMicUSB/rode-podmic-usb-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMicUSB/rode-podmic-usb-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMicUSB/rode-podmic-usb-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMicUSB/rode-podmic-usb-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMicUSB/rode-podmic-usb-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMicUSB/rode-podmic-usb-6.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Rode/microphone/PodMicUSB/rode-podmic-usb-7.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMicUSB/rode-podmic-usb-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMicUSB/rode-podmic-usb-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMicUSB/rode-podmic-usb-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMicUSB/rode-podmic-usb-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMicUSB/rode-podmic-usb-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMicUSB/rode-podmic-usb-6.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Rode/microphone/PodMicUSB/rode-podmic-usb-7.jpg',
      ],
    },
  },
  {
    sku: 'Neumann-TLM-107-BK-Studio-Set',
    stock: 2,
    company: 'Neumann',
    unit: 'TLM 107 BK Studio Set',
    description: 'Extremely versatile and surprisingly affordable!',
    price: 1550.0,
    productshowcase: false,
    category: 'microphones',
    polarPattern: ['omni', 'wide-cardioid', 'cardioid', 'hyper-cardioid', 'figure-8'],
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Neumann/TLM 107 BK Studio Set/neumann-tlm-107-bk-studio-set-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-660x660/Neumann/TLM 107 BK Studio Set/neumann-tlm-107-bk-studio-set-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-1000x1000/Neumann/TLM 107 BK Studio Set/neumann-tlm-107-bk-studio-set-1.jpg'],
    },
  },
  {
    sku: 'Neumann-TLM-107-Studio-Set',
    stock: 2,
    company: 'Neumann',
    unit: 'TLM 107 Studio Set',
    description: 'Extremely versatile and surprisingly affordable!',
    price: 1550.0,
    productshowcase: false,
    category: 'microphones',
    polarPattern: ['omni', 'wide-cardioid', 'cardioid', 'hyper-cardioid', 'figure-8'],
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Neumann/TLM 107 Studio Set/neumann-tlm-107-studio-set-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-660x660/Neumann/TLM 107 Studio Set/neumann-tlm-107-studio-set-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-1000x1000/Neumann/TLM 107 Studio Set/neumann-tlm-107-studio-set-1.jpg'],
    },
  },
  {
    sku: 'Neumann-TLM-107-BK',
    stock: 2,
    company: 'Neumann',
    unit: 'TLM 107 BK',
    description: 'Extremely versatile and surprisingly affordable!',
    price: 1450.0,
    productshowcase: false,
    category: 'microphones',
    polarPattern: ['omni', 'wide-cardioid', 'cardioid', 'hyper-cardioid', 'figure-8'],
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Neumann/TLM 107 BK/neumann-tlm-107-bk-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-660x660/Neumann/TLM 107 BK/neumann-tlm-107-bk-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-1000x1000/Neumann/TLM 107 BK/neumann-tlm-107-bk-1.jpg'],
    },
  },
  {
    sku: 'Neumann-TLM-107',
    stock: 2,
    company: 'Neumann',
    unit: 'TLM 107',
    description: 'Extremely versatile and surprisingly affordable!',
    price: 1450.0,
    productshowcase: false,
    category: 'microphones',
    polarPattern: ['omni', 'wide-cardioid', 'cardioid', 'hyper-cardioid', 'figure-8'],
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Neumann/TLM 107/neumann-tlm-107-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-660x660/Neumann/TLM 107/neumann-tlm-107-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-1000x1000/Neumann/TLM 107/neumann-tlm-107-1.jpg'],
    },
  },
  {
    sku: 'schiit-fulla',
    stock: 2,
    company: 'Schiit',
    unit: 'Fulla',
    description: 'Fulla E is a great DAC/amp with top-shelf components—that also has a very nice microphone input, too. ',
    price: 136.0,
    productshowcase: false,
    category: 'amps-dacs',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/Fulla/schiit-fulla-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/Fulla/schiit-fulla-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/Fulla/schiit-fulla-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/Fulla/schiit-fulla-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/Fulla/schiit-fulla-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/Fulla/schiit-fulla-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/Fulla/schiit-fulla-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/Fulla/schiit-fulla-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/Fulla/schiit-fulla-3.jpg',
      ],
    },
  },
  {
    sku: 'schiit-hel',
    stock: 2,
    company: 'Schiit',
    unit: 'Hel',
    description: 'Plug Hel 2E in to any PC, Mac, PS4, PS5, or Switch, and you’ll get tremendous sound…and you’ll also sound amazing to all of your friends.',
    price: 262.0,
    productshowcase: false,
    category: 'amps-dacs',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/Hel/schiit-hel-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/Hel/schiit-hel-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/Hel/schiit-hel-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/Hel/schiit-hel-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/Hel/schiit-hel-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/Hel/schiit-hel-6.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/Hel/schiit-hel-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/Hel/schiit-hel-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/Hel/schiit-hel-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/Hel/schiit-hel-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/Hel/schiit-hel-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/Hel/schiit-hel-6.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/Hel/schiit-hel-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/Hel/schiit-hel-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/Hel/schiit-hel-3.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/Hel/schiit-hel-4.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/Hel/schiit-hel-5.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/Hel/schiit-hel-6.jpg',
      ],
    },
  },
  {
    sku: 'schiit-magni+-black',
    stock: 2,
    company: 'Schiit',
    unit: 'Magni+ (Black)',
    description: 'Magni+: Exotic, current-feedback, all-discrete design, high-spec sorted potentiometer, high-end thin-film resistors, silicon capacitors. ',
    price: 145.0,
    productshowcase: false,
    category: 'amps',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/magni+-black/schiit-magni+-black-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/magni+-black/schiit-magni+-black-2.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/magni+-black/schiit-magni+-black-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/magni+-black/schiit-magni+-black-2.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/magni+-black/schiit-magni+-black-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/magni+-black/schiit-magni+-black-2.jpg',
      ],
    },
  },
  {
    sku: 'schiit-magni+-silver',
    stock: 2,
    company: 'Schiit',
    unit: 'Magni+ (Silver)',
    description: 'Magni+: Exotic, current-feedback, all-discrete design, high-spec sorted potentiometer, high-end thin-film resistors, silicon capacitors. ',
    price: 145.0,
    category: 'amps',
    productshowcase: false,
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/magni+-silver/schiit-magni+-silver-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/magni+-silver/schiit-magni+-silver-2.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/magni+-silver/schiit-magni+-silver-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/magni+-silver/schiit-magni+-silver-2.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/magni+-silver/schiit-magni+-silver-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/magni+-silver/schiit-magni+-silver-2.jpg',
      ],
    },
  },
  {
    sku: 'schiit-magnius',
    stock: 2,
    company: 'Schiit',
    unit: 'Magnius',
    description: 'Magnius delivers high power, superb measurements, and best volume control in its price class. It is also designed and built in California, USA. ',
    price: 262.0,
    productshowcase: false,
    category: 'amps',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/magnius/schiit-magnius-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/magnius/schiit-magnius-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/Schiit/amp/magnius/schiit-magnius-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/magnius/schiit-magnius-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/magnius/schiit-magnius-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/Schiit/amp/magnius/schiit-magnius-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/magnius/schiit-magnius-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/magnius/schiit-magnius-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/Schiit/amp/magnius/schiit-magnius-3.jpg',
      ],
    },
  },
  {
    sku: 'apos-topping-a90-discrete-black',
    stock: 2,
    company: 'Apos',
    unit: 'Topping A90 Discrete (Black)',
    description:
      '“Mr. Clean.” “The Giant Killer.” “The Best Amp Ever.” These are a few of nicknames the TOPPING A90, our best-selling amplifier, has gained since its release. At its most basic level, it’s a balanced amp and pre-amp with tremendously clean and powerful output. At its broadest level, it’s become the benchmark by which all other solid state amplifiers below $1,000 are judged.',
    price: 599.0,
    category: 'amps',
    productshowcase: false,
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Apos/amp/topping-a90-discrete/apos-topping-a90-discrete-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-660x660/Apos/amp/topping-a90-discrete/apos-topping-a90-discrete-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-1000x1000/Apos/amp/topping-a90-discrete/apos-topping-a90-discrete-1.jpg'],
    },
  },
  {
    sku: 'apos-topping-dx3-pro+',
    stock: 2,
    company: 'Apos',
    unit: 'Topping DX3 Pro+',
    description:
      'The TOPPING DX3 Pro+ DAC/Amp is TOPPING’s upgrade of their classic DX3 Pro. With a new Bluetooth chip and DAC chip, the Pro+ outperforms its predecessor while also coming in at a lower price point. The Pro+ has 60% lower THD+N (DAC), 85% lower THD+N (HPA), over 100% more power, and 90% lower output impedance than the DX3 Pro (LDAC version). ',
    price: 199.0,
    category: 'amps-dacs',
    productshowcase: false,
    images: {
      small: ['/src/ecommerce/assets/production-images/compressed-products-300x300/Apos/amp/topping-dx3-pro+/apos-topping-dx3-pro+-1.jpg'],
      medium: ['/src/ecommerce/assets/production-images/compressed-products-660x660/Apos/amp/topping-dx3-pro+/apos-topping-dx3-pro+-1.jpg'],
      large: ['/src/ecommerce/assets/production-images/compressed-products-1000x1000/Apos/amp/topping-dx3-pro+/apos-topping-dx3-pro+-1.jpg'],
    },
  },
  {
    sku: 's.m.s.l-sh-6-black',
    stock: 2,
    company: 'S.M.S.L',
    unit: 'SH-6 (Black)',
    description: 'Ultra-low distortion precision feedback circuit, distortion as low as 0.00006%! ',
    price: 119.99,
    productshowcase: false,
    category: 'amps',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/S.M.S.L/sh-6-black/smsl-sh-6-black-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/S.M.S.L/sh-6-black/smsl-sh-6-black-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/S.M.S.L/sh-6-black/smsl-sh-6-black-3.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/S.M.S.L/sh-6-black/smsl-sh-6-black-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/S.M.S.L/sh-6-black/smsl-sh-6-black-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/S.M.S.L/sh-6-black/smsl-sh-6-black-3.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/S.M.S.L/sh-6-black/smsl-sh-6-black-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/S.M.S.L/sh-6-black/smsl-sh-6-black-2.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/S.M.S.L/sh-6-black/smsl-sh-6-black-3.jpg',
      ],
    },
  },
  {
    sku: 's.m.s.l-sh-6-silver',
    stock: 2,
    company: 'S.M.S.L',
    unit: 'SH-6 (Silver)',
    description: 'Ultra-low distortion precision feedback circuit, distortion as low as 0.00006%! ',
    price: 119.99,
    productshowcase: false,
    category: 'amps',
    images: {
      small: [
        '/src/ecommerce/assets/production-images/compressed-products-300x300/S.M.S.L/sh-6-silver/smsl-sh-6-silver-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-300x300/S.M.S.L/sh-6-silver/smsl-sh-6-silver-2.jpg',
      ],
      medium: [
        '/src/ecommerce/assets/production-images/compressed-products-660x660/S.M.S.L/sh-6-silver/smsl-sh-6-silver-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-660x660/S.M.S.L/sh-6-silver/smsl-sh-6-silver-2.jpg',
      ],
      large: [
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/S.M.S.L/sh-6-silver/smsl-sh-6-silver-1.jpg',
        '/src/ecommerce/assets/production-images/compressed-products-1000x1000/S.M.S.L/sh-6-silver/smsl-sh-6-silver-2.jpg',
      ],
    },
  },
];
