import type { spotifyIso } from '~/spotify-visualizer/composables/const/spotifyIso';

export type SpotifyPathParams = {
  id: string;
  ids: number[];
  category_id: string;
  genres: string[];
  market: keyof typeof spotifyIso.market;
  markets: (keyof typeof spotifyIso.market)[];
  locale: keyof typeof spotifyIso.market;
  limit: number;
  offset: number;
  additional_types: string;
  device_id: string;
  device_ids: string[];
  play: boolean;
  position_ms: number;
  state: 'track' | 'context' | 'off';
  volume_percent: number;
  after: number;
  before: number;
  uri: string;
  playlist_id: string;
  fields: string;
  uris: string[];
  position: number;
  user_id: string;
  q: 'album' | 'artist' | 'track' | 'year' | 'upc' | 'tag:hipster' | 'tag:new' | 'isrc' | 'genre';
  type: string[];
  include_external: 'audio';
  seed_artists: string[];
  seed_genres: string[];
  seed_tracks: string[];
  min_acousticness: number;
  max_acousticness: number;
  target_acousticness: number;
  min_danceability: number;
  max_danceability: number;
  target_danceability: number;
  min_duration_ms: number;
  max_duration_ms: number;
  target_duration_ms: number;
  min_energy: number;
  max_energy: number;
  target_energy: number;
  min_instrumentalness: number;
  max_instrumentalness: number;
  target_instrumentalness: number;
  min_key: number;
  max_key: number;
  target_key: number;
  min_liveness: number;
  max_liveness: number;
  target_liveness: number;
  min_loudness: number;
  max_loudness: number;
  target_loudness: number;
  min_mode: number;
  max_mode: number;
  target_mode: number;
  min_popularity: number;
  max_popularity: number;
  target_popularity: number;
  min_speechiness: number;
  max_speechiness: number;
  target_speechiness: number;
  min_tempo: number;
  max_tempo: number;
  target_tempo: number;
  min_time_signature: number;
  max_time_signature: number;
  target_time_signature: number;
  min_valence: number;
  max_valence: number;
  target_valence: number;
  time_range: string;
  include_groups: string[];
};
